baseurl: ""
remote_theme: mmistakes/so-simple-theme
title: "六组の妙妙屋"
description: "用来进行展示与分享的综合平台"
author:
  name: "王翾羽"
  qq: "1263854739"

navigation:
  - title: 首页
    url: /
  - title: 项目展示
    url: /projects/
  - title: 博客
    url: /blog/
  - title: 关于作者
    url: /about/

# 先注释分页，确认能正常构建后再逐步打开
# paginate: 5
# paginate_path: "/page:num/"
